src/Entity/Review.php
<?php

namespace App\Entity;

use App\Repository\ReviewRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ReviewRepository::class)
 */
class Review
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $rating;

    /**
     * @ORM\Column(type="string", length=1000)
     */
    private $review;

    /**
     * @ORM\ManyToOne(targetEntity=User::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $fk_userId;

    /**
     * @ORM\ManyToOne(targetEntity=Product::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $fk_productId;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getRating(): ?int
    {
        return $this->rating;
    }

    public function setRating(int $rating): self
    {
        $this->rating = $rating;

        return $this;
    }

    public function getReview(): ?string
    {
        return $this->review;
    }

    public function setReview(string $review): self
    {
        $this->review = $review;

        return $this;
    }

    public function getFkUserId(): ?User
    {
        return $this->fk_userId;
    }

    public function setFkUserId(?User $fk_userId): self
    {
        $this->fk_userId = $fk_userId;

        return $this;
    }

    public function getFkProductId(): ?Product
    {
        return $this->fk_productId;
    }

    public function setFkProductId(?Product $fk_productId): self
    {
        $this->fk_productId = $fk_productId;

        return $this;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Entity\Location;
use App\Entity\Product;
use App\Entity\Review;
use App\Entity\ShoppingCart;
use App\Entity\User;
use App\Form\LocationType;
use App\Form\ReviewType;
use App\Form\UserType;
use App\Repository\ProductRepository;
use App\Repository\ReviewRepository;
use App\Repository\ShoppingCartRepository;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Service\FileUploader;

/**
 * @Route("/home")
 */
class HomeController extends AbstractController
{
    /**
     * @Route("/cart/{id}", name="app_cart_add", methods={"GET"})
     */
    public function addCart($id, Product $product, ShoppingCartRepository $shopcart, Request $request): Response
    {
        $amount = $request->query->get('amount');
        $stock = $product->getStock();
        // dd($stock);
        if($stock - $amount < 0){
            $this->addFlash('notice', 'Ordering amount is bigger than stock.');
            return $this->redirectToRoute('app_product_show', ['id' => $id]);
        }
        else{
            $userid = $this->getUser();
            $cart = $shopcart->findOneBy(array('fk_userId' => $userid, 'fk_productId' => $id, 'fk_order' => NULL));
            // dd($cart);
            if($cart){
                $oldamount = $cart->getAmount();
                $newamount = $oldamount + $amount;
                if($stock - $newamount < 0){
                    $this->addFlash('notice', 'The new total ordering amount would be bigger than stock.');
                    return $this->redirectToRoute('app_product_show', ['id' => $id]);
                }
                else{
                    $cart->setAmount($newamount);
                    $shopcart->add($cart);
                }
            }
            else{
                $cart = new ShoppingCart();
                $cart->setFkUserId($this->getUser());
                $cart->setFkProductId($product);
                $cart->setAmount($amount);
                // dd($cart);
                $shopcart->add($cart);
            }

            return $this->redirectToRoute('app_product_show', ['id' => $id]);
        }
    }

    /**
     * @Route("/cart", name="app_cart_show", methods={"GET"})
     */
    public function showCart(ShoppingCartRepository $shopcart): Response
    {
        $userid = $this->getUser();
        // dd($userid);
        $items = $shopcart->findBy(['fk_userId' => $userid, 'fk_order' => NULL]);
        // dd($items);
        $total = 0;
        foreach($items as $val){
            $price = $val->getFkProductId()->getPrice();
            $discount = $val->getFkProductId()->getDiscount();
            $amount = $val->getAmount();
            $total += $price * ((100-$discount)/100) * $amount;
        }

        return $this->render('home/cart.html.twig', [
            'items' => $items,
            'total' => $total,
        ]);
    }

    /**
     * @Route("/cart/delete/{id}", name="app_cart_delete", methods={"GET"})
     */
    public function deleteCartItem(ShoppingCartRepository $shopcart, $id): Response
    {
        $userid = $this->getUser();
        // dd($userid);
        $item = $shopcart->find($id);
        // dd($item);
        $shopcart->remove($item);

        return $this->redirectToRoute('app_cart_show');
    }

    /**
     * @Route("/order", name="app_cart_order") // try "/cart/order" for an error
     */
    public function orderCart(ShoppingCartRepository $shopcart): Response
    {
        $userid = $this->getUser();
        $items = $shopcart->findBy(['fk_userId' => $userid, 'fk_order' => NULL]);
        $error = false;
        foreach($items as $val){
            $amount = $val->getAmount();
            $stock = $val->getFkProductId()->getStock();
            if($stock - $amount < 0){
                $error = true;
                break;
            }

        }

        if($error){
            $this->addFlash('notice', 'Order amount is bigger than stock! Program anything to do something about this');
            return $this->redirectToRoute('app_home');
        }
        else{
            return $this->redirectToRoute('app_paypal');
        }
    }

    /**
     * @Route("/review/{id}", name="app_product_review")
     */
    public function reviewProduct($id, Request $request, ProductRepository $product, ReviewRepository $revrep): Response
    {
        $review = new Review();
        $text = $request->query->get('review');
        $rating = $request->query->get('rating3');
        $user = $this->getUser();
        $prodid = $product->find($id);
        $review->setFkUserId($user);
        $review->setFkProductId($prodid);
        $review->setRating($rating);
        $review->setReview($text);
        $revrep->add($review);

        return $this->redirectToRoute('app_product_show', ['id' => $id]);
    }

    /**
     * @Route("/review/{id}/delete/{prodid}", name="app_review_delete")
     */
    public function deleteReview($id, Request $request, ReviewRepository $revrep, $prodid): Response
    {
        $review = $revrep->find($id);
        $revrep->remove($review);

        return $this->redirectToRoute('app_product_show', ['id' => $prodid]);
    }

    /**
     * @Route("/show", name="app_user_show", methods={"GET"})
     */
    public function show(): Response
    {
        return $this->render('user/show.html.twig', [
            'user' => $this->getUser(),
        ]);
    }

    /**
     * @Route("/edit", name="app_user_edit", methods={"GET", "POST"})
     */
    public function edit(FileUploader $fileUploader, Request $request, UserRepository $userRepository, EntityManagerInterface $entityManager, ManagerRegistry $doctrine): Response
    {
        $user = $this->getUser();
        $loc = new Location();
        $loc->setZip($user->getFkLocation()->getZip());
        $loc->setCity($user->getFkLocation()->getCity());
        $loc->setCountry($user->getFkLocation()->getCountry());

        $form = $this->createForm(UserType::class, $user);
        $formloc = $this->createForm(LocationType::class, $loc);
        $form->handleRequest($request);
        $formloc->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            // handle location (available as fk in user entity)
            
            $country = $formloc->get('country')->getData();
            $city = $formloc->get('city')->getData();
            $zip = $formloc->get('zip')->getData();
            $location = $doctrine->getRepository(Location::class)->findOneBy(array('country' => $country, 'city' => $city, 'zip' => $zip));
            // if country is found in location table (1st column), loop through and check if city and zip also exist
            if(!$location){
                $location = new Location();
                $location->setCity($city);
                $location->setCountry($country);
                $location->setZip($zip);

                $entityManager->persist($location);
                $entityManager->flush();
            }

            $pictureFile = $form->get('pictureUrl')->getData();
            //pictureUrl is the name given to the input field
            if ($pictureFile) {
                $pictureFileName = $fileUploader->upload($pictureFile);
                $user->setPicture($pictureFileName);
            }
            $user->setFkLocation($location);
            $userRepository->add($user);
            return $this->redirectToRoute('app_user_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('user/edit.html.twig', [
            'user' => $user,
            'form' => $form,
            'formloc' => $formloc,
        ]);
    }

}

templates/home/cart.html.twig
{% extends 'base.html.twig' %}
{% block stylesheets %}
     <link rel="stylesheet" href="{{asset('style.css')}}">
{% endblock %}
{% block title %}Cart index{% endblock %}
{% block head %}



{% endblock %}

{% block body %}
     <link rel="stylesheet" href="{{asset('cart.css')}}">

   <body>
    <div class="card mt-5 mb-5">
        <div class="row">
            <div class="col-md-8 cart mt-5">
                <div class="title">
                    <div class="row">
                        <div class="col">
                            <h4><b>Shopping Cart</b></h4>
                        </div>
                        <div class="col align-self-center text-right text-muted" style="margin-left: 5px;"></div>
                    </div>
                </div>
                 {% for item in items %}
                <div class="row border-top border-bottom">
                    <div class="row main align-items-center">
                        <div class="col-2"><img id="cartimage" class="img-fluid" src="{{asset('pictures/'~ item.fkProductId.picture)}}"></div>
                        <div class="col">
                            <div class="row text-muted">{{item.fkProductId.name}}</div>
                            <div class="row">{{item.amount}}</div>
                            <div class="row">{{ item.fkProductId.price * item.amount }} ({{ item.fkProductId.price }})</div>
                        </div>
                        <a class="btn" href="{{ path('app_cart_delete', {'id': item.id}) }}">delete</a>
                        <div class="col">&euro;{{ item.fkProductId.price}}  <span class="close">&#10005;</span></div>
                    </div>
                </div>
                {% else %}
                    <div class="row border-top border-bottom">
                    <div class="row main align-items-center">
                        <div class="row">no records found</div>
                        <div class="col">
                            
                        </div>
                      
                    </div>
                </div>
                {% endfor %}
              
                
                <div class="back-to-shop"><a href="{{ path('app_homeproducts') }}">&leftarrow;</a><span class="text-muted">Back to shop</span></div>
            </div>
            <div class="col-md-4 summary ">
                <div>
                    <h5><b>Summary</b></h5>
                </div>
                <hr>
                <div class="row">
                    <div class="col" style="padding-left:1;"></div>
                    <div class="col text-right">&euro; </div>
                </div>
                <form class="form">
                    <p class="fs-5">SHIPPING</p>
                    <p class="fs-5">Standard-Delivery</p>


                </form>
                <div class="row" style="border-top: 1px solid rgba(0,0,0,.1); padding: 10vh 0;">
                    <div class="col">TOTAL PRICE</div>
                    <div class="col text-right">{{ total }}€</div>
                </div> <a href="{{ path('app_cart_order') }}"><button class="btn1">CHECKOUT</button></a>
            </div>
        </div>
    </div>
{% block script %}
 <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>

{% endblock %}
   
</body>

{% endblock %}

templates/home/contact.html.twig
{% extends "base.html.twig" %}

{% block stylesheets %}
<style>
    #map {
        height: 35vw;
        width: 60vw;
    }
</style>
{% endblock %}

{% block body %}
<p class="fs-5">Mail us: <a href="mailto:symfonymailer2022@gmail.com">symfonymailer2022@gmail.com</a></p>
<center><div id="map"></div></center>

<script>
    let markers = [];
    function initMap() {
        var mlocation = {
            lat: 48.20849,
            lng: 16.37208
        };

        map = new google.maps.Map(document.getElementById('map'), {
            center: mlocation,
            zoom: 12
        });

        let marker = new google.maps.Marker({
            map: map,
            position: mlocation
        });
        markers.push(marker);
    };
    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBtjaD-saUZQ47PbxigOg25cvuO6_SuX3M&callback=initMap" async defer></script>
{% endblock %}

templates/home/home_products.html.twig
{% extends "base.html.twig" %}
{% block stylesheets %}<link rel="stylesheet" href="{{ asset("style2.css")}}">
<link rel="stylesheet" href="{{ asset("style.css")}}">{% endblock %}

{% block body %}

    <div class="container">
        <div class="text-center">
            <div class="row">
                <div class="align-items-center  mb-5 mt-5 ">
                    <h2 class="mico mt-5">Products</h2>
                
                </div>
                {% for product in products %}
                    <div class="col-lg-4 col-md-6 col-sm-12 ">
                        <a href="{{path('app_product_show', {'id': product.id})}}"><img src="{{asset('pictures/' ~ product.picture)}}" class="mb-3 maca"></a>
                        <a href="{{path('app_product_show', {'id': product.id})}}">{{product.name}}</a>
                        {# <p class="mt-2">STARS FROM REVIEWS</p> #}
                        <p class="fs-4">€ {{product.price}} ,-</p>
                    </div>
                {% endfor %}    
            </div>
        </div>
    </div>
{% endblock %}

templates/home/index.html.twig
{% extends "base.html.twig" %} {% block body %}


    <div class="slide text-center justify-content-center">
        <img src="{{asset('pictures/5328.jpg')}}" class="show">
        <div class="content"> 
            <h3 class="move"> Move yourself with music </h3>
        <a href="{{ path('app_homeproducts') }}"><input type="button" class="btn btn-light btnfont fs-5" value="Show products"></a>
            
        </div>
    </div>


<div class="slideshow-container bg-light">
    <div class="mySlides">
        <h2>Click & collect</h2>
        <i>Online bestellen und direkt im Store abholen</i>
    </div>

    <div class="mySlides">
        <h2>Speziell für Sie</h2>
        <i>Jetzt Onlineberatung über Whatsapp.</i>
    </div>

    <div class="mySlides">
        <h2>Gratis Versand</h2>
        <i>Bestellen Sie über €30,- und kriegen Sie ihre Bestellung ganz beiuem gratis nachhause geschickt</i>
    </div>

    <a class="prev" onclick="plusSlides(-1)">❮</a>
    <a class="next" onclick="plusSlides(1)">❯</a>

    <div class="dot-container ">
        <span class="dot" onclick="currentSlide(1)"></span>
        <span class="dot" onclick="currentSlide(2)"></span>
        <span class="dot" onclick="currentSlide(3)"></span>
    </div>

</div>

<div class="text-center mt-5 mb-5">
    <h2>Popular Items</h2>
    <p class="fs-5">These are our most sold items</p>
</div>
<div class="container d-flex text-center">
    <div class="row">
        <div class="col-lg-4 col-md-6">
            <a href="{{ path('app_product_show', {'id': products[0].id}) }}">
                <img src="{{asset('pictures/' ~ products[0].picture)}}" style="max-width: 100%;" alt="">
            </a>
            <p class="mt-4 container fs-5">Originally created for the hardwood, the Dunk later took to the streets—and as they say, the rest is history. More than 35 years after its debut, the silhouette still delivers bold, defiant style and remains a coveted look for crews across both sport and culture</p>
            <p class="fs-5">€{{ products[0].price }},-</p>
        </div>
        <div class="col-lg-4 col-md-6">
            <a href="{{ path('app_product_show', {'id': products[1].id}) }}">
                <img src="{{asset('pictures/' ~ products[1].picture)}}" style="max-width: 100%;" alt="">
            </a>
            <p class="mt-4 container fs-5">Originally a classic Nike hoops shoe, the Dunk was organically adopted by skate culture—and in time re-engineered for Nike SB.</p>
            <p class="fs-5">€{{ products[1].price }},-</p>
        </div>
        <div class="col-lg-4 col-md-6 mb-5">
            <a href="{{ path('app_product_show', {'id': products[2].id}) }}">
                <img src="{{asset('pictures/' ~ products[2].picture)}}" style="max-width: 100%;" alt="">
            </a>
            <p class="mt-4 container fs-4">A paisley Swoosh channels vintage vibes back onto the street, while the plush, low-cut collar lets you take your game anywhere.</p>
            <p class="fs-5">€{{ products[2].price }},-</p>
        </div>
    </div>
</div>


<div class="card mb-3 boxborder bg-light">
    <div class="row g-0">
        <div class="col-md-7">
            <img src="{{asset('pictures/151-1511522_music-headphones.jpg')}}" class="img-fluid rounded-start" alt="...">
        </div>
        <div class="col-md-5 d-flex align-items-center text-end">
            <div class="card-body m-5">
                <h3 class="card-title">Discover our store and get in love with your new headphones.</h3>
                <p class="card-text fs-5">We got all kind of brands. Doesnt matter where you go, we got your back! Discover our store and make yourself happy!</p>
                <a href="{{ path('app_filter', {filter: 4}) }}"><input type="button" class="btn btn-dark btnfont fs-5" value="Discover more "></a>
            </div>
        </div>
    </div>
</div>



<section>
    <div class="reveal text-center">
        <h2>Our categories</h2>
        
        <div class="text-container row mb-5">
            <div class="col-lg-4 col-md-6 text-box">
                <h3 class=" m-3 pio">In-ear headphones & earbuds</h3>
                <a href="{{ path('app_filter', {filter: 1}) }}">
                    <img class="slikaop" src="{{asset('pictures/31lKGXyonvL.jpg')}}">
                </a>
            </div>
            <div class="col-lg-4 col-md-6 text-box">
                <h3 class=" m-3 pio">Over & on-ear headphones</h3>
                <a href="{{ path('app_filter', {filter: 2}) }}">
                    <img class="slikaop" src="{{asset('pictures/61eJhLsaV0L-63bee682dcdb8.jpg')}}">
                </a>
            </div>
            <div class="col-lg-4 col-md-6 text-box">
                <h3 class="m-3 pio">Wireless headphones</h3>
                <a href="{{ path('app_filter', {filter: 3}) }}">
                    <img class="slikaop" src="{{asset('pictures/audiosanctuary_audeze_lcd_i3_1.jpg')}}">
                </a>
            </div>
        </div>
        <div>
             <a href="{{ path('app_homeproducts') }}" class="btn btn-dark btnfont fs-5">See more!</a>
        </div>
    </div>
</section>



<div class="card mb-3 boxborder">
    <div class="row g-0">
        <div class="col-lg-6 col-md-12 col-sm-12 d-flex align-items-center">
            <div class="card-body text-start" style="max-height: 320px;">
                <img src="{{asset('pictures/ig2.png')}}" style="max-height: 80px;" alt="">
                <h3 class="card-title text-uppercase socialmediaText mt-3 ">Get inspired by Instagram</h3>
                <p class="card-text fs-5">Are you looking for new headphones? Get in touch with us on Instagram. We are posting daily</p>
                <input type="button" value="Get in touch!" class="btn btn-dark btnfont mt-2 fs-5">
            </div>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-12 igpicture">
            <div class="random">
                <img src="{{asset('pictures/eee9H8z.jpg')}}" class="img-fluid image" alt="...">
                <div class="middle">
                    <div class="igicon">
                        <a href=""><img class="igcolor" src="{{asset('pictures/igicon.png')}}"></a>
                    </div>
                </div>
            </div>
        </div>
         
    </div>
</div>



<section class="absolute">
    <div class="reveal text-center absolute">
        <h2>TOP PICKS</h2>
        <p class="text-center fs-5">These are our alltime top picks. Click on the picture and get directly to your headphones.</p>
        <div class="text-container row mb-5">
                <div class="col-lg-4 col-md-6">
                    <a href="{{ path('app_product_show', {'id': products[2].id}) }}">
                        <img src="{{asset('pictures/' ~ products[2].picture)}}" class="slikaop" alt="">
                    </a>
                    <p class="fs-5">€{{ products[2].price }},-</p>
                </div> 
                <div class="col-lg-4 col-md-6">
                    <a href="{{ path('app_product_show', {'id': products[3].id}) }}">
                        <img src="{{asset('pictures/' ~ products[3].picture)}}" class="slikaop" alt="">
                    </a>
                    <p class="fs-5">€{{ products[3].price }},-</p>
                </div> 
                <div class="col-lg-4 col-md-6">
                    <a href="{{ path('app_product_show', {'id': products[8].id}) }}">
                        <img src="{{asset('pictures/' ~ products[8].picture)}}" class="slikaop" alt="">
                    </a>
                    <p class="fs-5">€{{ products[8].price }},-</p>
                </div> 
        </div>
        <div>
            <a href="{{ path('app_homeproducts') }}" class="btn btn-dark btnfont fs-5">Load more</a>
        </div>
    </div>
</section>
{% endblock %}